<div id="lander">
  <div class="padding_box">
    <div class="module">
      <h1>Content Page Title</h1>
      <div class="padding_box">
        <p> These Terms of Use govern your access to and use of the ApartmentGuide.com and its related family of websites (defined as the "Site" or “Sites”). Your access to and use of ApartmentGuide.com are expressly conditioned on your compliance with these Terms of Use. By accessing or using ApartmentGuide.com, you agree to be bound by these Terms of Use, our Privacy Policy, and any other terms, guidelines or rules that are applicable to any portion of ApartmentGuide.com that you may access, without limitation or qualification. For purposes of these Terms of Use, all references to "ApartmentGuide.com" or the “Site” include Consumer Source Inc. and its affiliates, subsidiaries and related Sites. </p>
        <p> These Terms of Use govern your access to and use of the ApartmentGuide.com and its related family of websites (defined as the "Site" or “Sites”). Your access to and use of ApartmentGuide.com are expressly conditioned on your compliance with these Terms of Use. By accessing or using ApartmentGuide.com, you agree to be bound by these Terms of Use, our Privacy Policy, and any other terms, guidelines or rules that are applicable to any portion of ApartmentGuide.com that you may access, without limitation or qualification. For purposes of these Terms of Use, all references to "ApartmentGuide.com" or the “Site” include Consumer Source Inc. and its affiliates, subsidiaries and related Sites. </p>
        <p> These Terms of Use govern your access to and use of the ApartmentGuide.com and its related family of websites (defined as the "Site" or “Sites”). Your access to and use of ApartmentGuide.com are expressly conditioned on your compliance with these Terms of Use. By accessing or using ApartmentGuide.com, you agree to be bound by these Terms of Use, our Privacy Policy, and any other terms, guidelines or rules that are applicable to any portion of ApartmentGuide.com that you may access, without limitation or qualification. For purposes of these Terms of Use, all references to "ApartmentGuide.com" or the “Site” include Consumer Source Inc. and its affiliates, subsidiaries and related Sites. </p>
        <p> These Terms of Use govern your access to and use of the ApartmentGuide.com and its related family of websites (defined as the "Site" or “Sites”). Your access to and use of ApartmentGuide.com are expressly conditioned on your compliance with these Terms of Use. By accessing or using ApartmentGuide.com, you agree to be bound by these Terms of Use, our Privacy Policy, and any other terms, guidelines or rules that are applicable to any portion of ApartmentGuide.com that you may access, without limitation or qualification. For purposes of these Terms of Use, all references to "ApartmentGuide.com" or the “Site” include Consumer Source Inc. and its affiliates, subsidiaries and related Sites. </p>
      </div>
    </div>
  </div>
</div>
